/**
 * Chronicles of War - Historical Eras & Unit Definitions
 * Spans Antiquity, Middle Ages, Renaissance, Modern Era, and 19th Century
 */

const ERAS = {
  antiquity: {
    id: 'antiquity',
    name: 'Antigüedad Clásica',
    period: '500 a.C. - 400 d.C.',
    theme: 'Legiones, Falanges y Catapultas',
    banner: '🏛️',
    description: 'La era del bronce y el hierro forjado. Formaciones masivas disciplinadas, escudos entrelazados y proyectiles balísticos.',
    units: {
      legion: {
        id: 'legion',
        name: 'Legión Romana',
        era: 'antiquity',
        category: 'infantry',
        symbol: 'X',
        badge: '⚔️',
        cost: 200,
        soldierCount: 48,
        cols: 12,
        rows: 4,
        health: 120,
        morale: 100,
        meleeDamage: 28,
        rangedDamage: 38, // Pilum throw
        range: 65,
        reloadTime: 8.0,
        maxVolleys: 2, // Pilum volleys before full melee
        speed: 38,
        armor: 0.35,
        weaponType: 'pilum',
        abilities: ['testudo', 'pilum_volley'],
        desc: 'Infantería pesada disciplinada. Lanza dos salvas de pilum perforante antes de trabar combate cerrado con gladius.'
      },
      phalanx: {
        id: 'phalanx',
        name: 'Falange Hoplita / Sarissa',
        era: 'antiquity',
        category: 'pikes',
        symbol: '|X|',
        badge: '🛡️',
        cost: 220,
        soldierCount: 48,
        cols: 12,
        rows: 4,
        health: 110,
        morale: 95,
        meleeDamage: 34,
        rangedDamage: 0,
        range: 0,
        speed: 30,
        armor: 0.40,
        weaponType: 'pike',
        pikeLength: 22,
        abilities: ['pike_wall'],
        desc: 'Muro erizado de lanzas largas. Inmune al choque frontal de caballería e infantería, pero muy vulnerable a los flancos.'
      },
      cavalry: {
        id: 'cavalry',
        name: 'Caballería Númida',
        era: 'antiquity',
        category: 'cavalry',
        symbol: '/',
        badge: '🐎',
        cost: 250,
        soldierCount: 24,
        cols: 8,
        rows: 3,
        health: 90,
        morale: 85,
        meleeDamage: 30,
        rangedDamage: 18,
        range: 110,
        reloadTime: 3.5,
        speed: 68,
        armor: 0.15,
        weaponType: 'bow',
        abilities: ['feigned_retreat'],
        desc: 'Jinetes ligeros y escurridizos. Hostigan a distancia con jabalinas y arcos, ideales para envolver líneas enemigas.'
      },
      ballista: {
        id: 'ballista',
        name: 'Balista de Torsión',
        era: 'antiquity',
        category: 'artillery',
        symbol: '●',
        badge: '🎯',
        cost: 350,
        soldierCount: 8,
        cols: 4,
        rows: 2,
        health: 70,
        morale: 70,
        meleeDamage: 8,
        rangedDamage: 90,
        range: 280,
        reloadTime: 7.0,
        speed: 22,
        armor: 0.10,
        weaponType: 'cannonball',
        abilities: ['pierce_shot'],
        desc: 'Ingeniería de asedio romana. Dispara dardos pesados capaces de atravesar filas enteras a gran distancia.'
      }
    }
  },

  medieval: {
    id: 'medieval',
    name: 'Edad Media',
    period: '500 - 1450',
    theme: 'Caballeros, Arcos Largos y Castillos',
    banner: '🏰',
    description: 'El apogeo de la caballería de placas y la letalidad de las lluvias de flechas de los arcos largos ingleses.',
    units: {
      knights: {
        id: 'knights',
        name: 'Caballeros Feudales',
        era: 'medieval',
        category: 'cavalry',
        symbol: '/',
        badge: '🐴',
        cost: 320,
        soldierCount: 24,
        cols: 8,
        rows: 3,
        health: 160,
        morale: 110,
        meleeDamage: 52, // Brutal shock charge
        rangedDamage: 0,
        range: 0,
        speed: 62,
        armor: 0.55,
        weaponType: 'melee',
        abilities: ['heavy_charge'],
        desc: 'Fuerza de choque imparable en campo abierto. Su carga derriba regimientos que no estén protegidos por picas o estacas.'
      },
      longbow: {
        id: 'longbow',
        name: 'Arqueros de Tiro Largo',
        era: 'medieval',
        category: 'ranged',
        symbol: '...',
        badge: '🏹',
        cost: 190,
        soldierCount: 40,
        cols: 10,
        rows: 4,
        health: 75,
        morale: 80,
        meleeDamage: 14,
        rangedDamage: 24,
        range: 240,
        reloadTime: 3.2,
        speed: 42,
        armor: 0.15,
        weaponType: 'bow',
        abilities: ['arrow_storm', 'deploy_stakes'],
        desc: 'Arqueros de tejo galés. Disparan densas salvas parabólicas por encima de obstáculos e inflijen graves bajas a distancia.'
      },
      men_at_arms: {
        id: 'men_at_arms',
        name: 'Hombres de Armas',
        era: 'medieval',
        category: 'infantry',
        symbol: 'X',
        badge: '🛡️',
        cost: 180,
        soldierCount: 48,
        cols: 12,
        rows: 4,
        health: 125,
        morale: 90,
        meleeDamage: 32,
        rangedDamage: 0,
        range: 0,
        speed: 36,
        armor: 0.45,
        weaponType: 'melee',
        abilities: ['shield_wall'],
        desc: 'Infantería acorazada con espadas bastardas y hachas de guerra. La columna vertebral defensiva en combate prolongado.'
      },
      catapult: {
        id: 'catapult',
        name: 'Fundíbulo / Trebuchet',
        era: 'medieval',
        category: 'artillery',
        symbol: '●',
        badge: '☄️',
        cost: 380,
        soldierCount: 8,
        cols: 4,
        rows: 2,
        health: 80,
        morale: 70,
        meleeDamage: 8,
        rangedDamage: 140,
        range: 320,
        reloadTime: 9.5,
        speed: 18,
        armor: 0.10,
        weaponType: 'cannonball',
        abilities: ['siege_breach'],
        desc: 'Arma de asedio de contrapeso. Lanza proyectiles colosales para pulverizar murallas y crear brechas transitables.'
      }
    }
  },

  renaissance: {
    id: 'renaissance',
    name: 'Renacimiento & Pike-and-Shot',
    period: '1492 - 1648',
    theme: 'La Batalla de Pavía & Tercios',
    banner: '⚜️',
    description: 'La revolución de la pólvora. Tercios españoles, cuadros de picas con mangas de arcabuceros y baluartes de traza italiana.',
    units: {
      tercio: {
        id: 'tercio',
        name: 'Tercio Español',
        era: 'renaissance',
        category: 'pikes',
        symbol: '|X|',
        badge: '🚩',
        cost: 280,
        soldierCount: 56,
        cols: 14,
        rows: 4,
        health: 140,
        morale: 120, // Iron morale
        meleeDamage: 36,
        rangedDamage: 35,
        range: 130,
        reloadTime: 5.5,
        speed: 32,
        armor: 0.40,
        weaponType: 'tercio_hybrid', // Central pikes + corner arquebuses
        pikeLength: 24,
        abilities: ['pike_wall', 'counter_march'],
        desc: 'La formación reina de Europa. Núcleo invulnerable de picas flanqueado por mangas de arcabuz que abren fuego continuo.'
      },
      arquebusiers: {
        id: 'arquebusiers',
        name: 'Manga de Arcabuceros',
        era: 'renaissance',
        category: 'ranged',
        symbol: '...',
        badge: '💥',
        cost: 180,
        soldierCount: 36,
        cols: 12,
        rows: 3,
        health: 80,
        morale: 85,
        meleeDamage: 15,
        rangedDamage: 42,
        range: 160,
        reloadTime: 5.0,
        speed: 40,
        armor: 0.20,
        weaponType: 'arquebus',
        abilities: ['kneel_fire', 'caracole'],
        desc: 'Tiradores con arcabuz de mecha. Gran penetración de armadura; generan densas nubes de humo blanco de pólvora negra.'
      },
      landsknecht: {
        id: 'landsknecht',
        name: 'Lansquenetes Doppelsöldner',
        era: 'renaissance',
        category: 'infantry',
        symbol: 'X',
        badge: '🗡️',
        cost: 210,
        soldierCount: 40,
        cols: 10,
        rows: 4,
        health: 110,
        morale: 95,
        meleeDamage: 45,
        rangedDamage: 0,
        range: 0,
        speed: 38,
        armor: 0.30,
        weaponType: 'melee',
        abilities: ['greatsword_sweep'],
        desc: 'Mercenarios alemanes armados con espadones Zweihänder. Especialistas en romper los bosques de picas enemigos en la brecha.'
      },
      culverin: {
        id: 'culverin',
        name: 'Culebrina de Bronce',
        era: 'renaissance',
        category: 'artillery',
        symbol: '●',
        badge: '💣',
        cost: 360,
        soldierCount: 8,
        cols: 4,
        rows: 2,
        health: 80,
        morale: 75,
        meleeDamage: 10,
        rangedDamage: 130,
        range: 340,
        reloadTime: 8.0,
        speed: 20,
        armor: 0.15,
        weaponType: 'cannonball',
        abilities: ['breach_walls'],
        desc: 'Pieza de artillería de asedio fundida en bronce. Pulveriza fortificaciones y derriba murallas con ensordecedores rugidos.'
      }
    }
  },

  modern: {
    id: 'modern',
    name: 'Edad Moderna & Ilustración',
    period: '1650 - 1790',
    theme: 'Fusiles de Pedernal, Bayonetas y Bastiones',
    banner: '🦅',
    description: 'La consolidación de la línea de fusilería con bayoneta de cubo, granaderos de asalto y fortalezas Vauban.',
    units: {
      line_infantry: {
        id: 'line_infantry',
        name: 'Infantería de Línea',
        era: 'modern',
        category: 'infantry',
        symbol: 'X',
        badge: '💂',
        cost: 190,
        soldierCount: 48,
        cols: 16,
        rows: 3,
        health: 95,
        morale: 90,
        meleeDamage: 25, // Bayonet
        rangedDamage: 38,
        range: 175,
        reloadTime: 4.2,
        speed: 38,
        armor: 0.15,
        weaponType: 'musket',
        abilities: ['rolling_volley', 'bayonet_charge'],
        desc: 'Regimiento de fusileros disciplinados. Descargas sucesivas por filas que destrozan la cohesión enemiga.'
      },
      grenadiers: {
        id: 'grenadiers',
        name: 'Granaderos de Asalto',
        era: 'modern',
        category: 'infantry',
        symbol: 'X',
        badge: '💣',
        cost: 260,
        soldierCount: 36,
        cols: 12,
        rows: 3,
        health: 125,
        morale: 115,
        meleeDamage: 38,
        rangedDamage: 44,
        range: 160,
        reloadTime: 4.2,
        speed: 36,
        armor: 0.25,
        weaponType: 'musket',
        abilities: ['grenade_throw', 'unyielding'],
        desc: 'Tropas de choque gigantescas con morriones altos. Moral imperturbable para tomar baluartes y brechas a punta de bayoneta.'
      },
      dragoons: {
        id: 'dragoons',
        name: 'Dragones Montados',
        era: 'modern',
        category: 'cavalry',
        symbol: '/',
        badge: '🐎',
        cost: 270,
        soldierCount: 24,
        cols: 8,
        rows: 3,
        health: 105,
        morale: 88,
        meleeDamage: 32,
        rangedDamage: 35,
        range: 150,
        reloadTime: 4.8,
        speed: 64,
        armor: 0.20,
        weaponType: 'musket',
        abilities: ['dismount_fire'],
        desc: 'Infantería montada de rápido despliegue. Capaces de disparar al trote y asaltar flancos vulnerables.'
      },
      twelve_pounder: {
        id: 'twelve_pounder',
        name: 'Batería de 12 Libras',
        era: 'modern',
        category: 'artillery',
        symbol: '●',
        badge: '💥',
        cost: 390,
        soldierCount: 8,
        cols: 4,
        rows: 2,
        health: 85,
        morale: 80,
        meleeDamage: 12,
        rangedDamage: 145,
        range: 360,
        reloadTime: 7.5,
        speed: 22,
        armor: 0.20,
        weaponType: 'cannonball',
        abilities: ['canister_shot'],
        desc: 'La columna vertebral de la artillería de campaña. Dispara bolas sólidas a distancia o botes de metralla devastadores a corta distancia.'
      }
    }
  },

  napoleonic: {
    id: 'napoleonic',
    name: 'Siglo XIX & Guerras Napoleónicas',
    period: '1799 - 1880',
    theme: 'Waterloo, Cuadros de Infantería y Cargas de Coraceros',
    banner: '👑',
    description: 'La cumbre del combate de armas combinadas en el siglo XIX: artillería a caballo, cuadros anti-caballería y fusiles estriados.',
    units: {
      imperial_guard: {
        id: 'imperial_guard',
        name: 'Vieja Guardia Imperial',
        era: 'napoleonic',
        category: 'infantry',
        symbol: 'X',
        badge: '🎖️',
        cost: 300,
        soldierCount: 48,
        cols: 16,
        rows: 3,
        health: 140,
        morale: 130, // The Guard never retreats
        meleeDamage: 36,
        rangedDamage: 46,
        range: 190,
        reloadTime: 3.8,
        speed: 38,
        armor: 0.20,
        weaponType: 'musket',
        abilities: ['square', 'pas_de_charge'],
        desc: 'Veteranos curtidos en cien batallas con colosales gorras de piel de oso. Moral heroica, marchan al frente bajo cualquier fuego.'
      },
      rifles: {
        id: 'rifles',
        name: 'Tiradores / 95th Rifles',
        era: 'napoleonic',
        category: 'ranged',
        symbol: '...',
        badge: '🎯',
        cost: 230,
        soldierCount: 30,
        cols: 15,
        rows: 2,
        health: 80,
        morale: 90,
        meleeDamage: 18,
        rangedDamage: 55,
        range: 260, // Long-range rifle
        reloadTime: 5.0,
        speed: 46,
        armor: 0.10,
        weaponType: 'rifle',
        abilities: ['skirmish_screen', 'snipe_officers'],
        desc: 'Uniforme verde de camuflaje y fusiles Baker estriados. Precisión letal a larga distancia para abatir oficiales enemigos.'
      },
      cuirassiers: {
        id: 'cuirassiers',
        name: 'Coraceros Pesados',
        era: 'napoleonic',
        category: 'cavalry',
        symbol: '/',
        badge: '⚔️',
        cost: 330,
        soldierCount: 24,
        cols: 8,
        rows: 3,
        health: 150,
        morale: 105,
        meleeDamage: 48,
        rangedDamage: 0,
        range: 0,
        speed: 65,
        armor: 0.50, // Steel breastplates reflect bullets
        weaponType: 'melee',
        abilities: ['heavy_charge'],
        desc: 'Ginetes gigantes con corazas de acero y sables de hoja recta. Destructores de líneas que no consigan formar en cuadro.'
      },
      grand_battery: {
        id: 'grand_battery',
        name: 'Gran Batería de Campaña',
        era: 'napoleonic',
        category: 'artillery',
        symbol: '●',
        badge: '💣',
        cost: 420,
        soldierCount: 8,
        cols: 4,
        rows: 2,
        health: 90,
        morale: 85,
        meleeDamage: 14,
        rangedDamage: 160,
        range: 380,
        reloadTime: 6.8,
        speed: 24,
        armor: 0.20,
        weaponType: 'cannonball',
        abilities: ['canister_shot', 'concentrated_barrage'],
        desc: 'La "Bella Hija del Emperador". Descargas continuas de hierro que pulverizan regimientos enteros y levantan nubes colosales de humo.'
      }
    }
  }
};

window.ERAS = ERAS;
